jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -20,8 +20,8 @@ pipeline {
         stage('Docker Build and Run') {
             steps {
                 script {
-                    sh "docker build -t ${APP_NAME}:latest ."
-                    sh "docker run -d -p 5000:5000 --name test-${APP_NAME} ${APP_NAME}:latest"
+                    bat "docker build -t %APP_NAME%:latest ."
+                    bat "docker run -d -p 5000:5000 --name test-%APP_NAME% %APP_NAME%:latest"
                 }
             }
         }
@@ -29,8 +29,8 @@ pipeline {
         stage('Trivy Security Scan') {
             steps {
                 script {
-                    sh """
-                        trivy image --format table --output trivy-report.txt ${APP_NAME}:latest || true
+                    bat """
+                    trivy image --format table --output trivy-report.txt %APP_NAME%:latest || exit 0
                     """
                 }
                 archiveArtifacts artifacts: 'trivy-report.txt', onlyIfSuccessful: false
@@ -43,10 +43,10 @@ pipeline {
                     $class: 'AmazonWebServicesCredentialsBinding',
                     credentialsId: "${AWS_CREDENTIALS_ID}"
                 ]]) {
-                    sh """
-                        aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}
-                        docker tag ${APP_NAME}:latest ${ECR_REPO}:latest
-                        docker push ${ECR_REPO}:latest
+                    bat """
+                    aws ecr get-login-password --region %AWS_REGION% | docker login --username AWS --password-stdin %ECR_REGISTRY%
+                    docker tag %APP_NAME%:latest %ECR_REPO%:latest
+                    docker push %ECR_REPO%:latest
                     """
                 }
             }
@@ -58,10 +58,10 @@ pipeline {
                     $class: 'AmazonWebServicesCredentialsBinding',
                     credentialsId: "${AWS_CREDENTIALS_ID}"
                 ]]) {
-                    sh """
-                        cd terraform
-                        terraform init
-                        terraform apply -auto-approve
+                    bat """
+                    cd terraform
+                    terraform init
+                    terraform apply -auto-approve
                     """
                 }
             }
@@ -71,14 +71,14 @@ pipeline {
     post {
         always {
             echo 'Cleaning up Docker container...'
-            sh "docker stop test-${APP_NAME} || true"
-            sh "docker rm test-${APP_NAME} || true"
+            bat "docker stop test-%APP_NAME% || exit 0"
+            bat "docker rm test-%APP_NAME% || exit 0"
         }
         success {
             echo ' Pipeline completed successfully.'
         }
         failure {
-            echo 'Pipeline failed.'
+            echo ' Pipeline failed.'
         }
     }
 }
